### PR TITLE
SL-218: Azure SQL Server advanced data security does not have an emai…

### PR DESCRIPTION
**Pull request by xuwangpalo**
…l alert recipient

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by xuwangpalo** [comment]
> email is a mandatory field in threat_detection_policy block. We might not need this policy or need to change it.

it's optioanl, see:
https://www.terraform.io/docs/providers/azurerm/r/sql_database.html

**Comment by ngarg-panw** [comment]
Yes, the docs are not updated. If you try to create a terraform plan without email, it will throw error.
Checkout this thread: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1974

**Comment by xuwangpalo** [comment]
Good finding! I can remove the email-addresses check clause. The policy checks if  threat-detection is enabled for the database. What do you think?

**Comment by ngarg-panw** [comment]
Since email is a required field, we don't need this policy. Closing it.

**Comment by ngarg-panw** [comment]
Since email is a required field, we don't need this policy. Closing it.

**Pull request closed without merging**
